services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    networks:
      - caddy_network
    deploy:
      resources:
        limits:
          memory: 1G       # Limitar a 1 GB de memoria
          cpus: "1"        # Limitar a 1 CPU
    healthcheck: 
      interval: 10s
      retries: 10
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      timeout: 2s
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8082:80"
    networks:
      - caddy_network
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  caddy_network:
    external: true