services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    restart: always
    networks:
      - caddy_network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env.dev
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8082:80"
    networks:
      - caddy_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  caddy_network:
    external: true